In [11]:
import pandas as pd
import numpy as np

# Paper Predictions

In [12]:
paper_cancer_genes = pd.read_csv('../../../../../../../../s/project/gene_embedding/cancer_pred/emogi_prediction.tsv', sep='\t')
paper_cancer_genes

,gene_id,pred,fold,label,original_score,method,model
0,ENSG00000133703,5.293305,0,True,5.293305,score_only,emogi
1,ENSG00000141646,5.293240,0,True,5.293240,score_only,emogi
2,ENSG00000197694,5.293193,0,False,5.293193,score_only,emogi
3,ENSG00000166949,5.293138,0,True,5.293138,score_only,emogi
4,ENSG00000157764,5.293047,0,True,5.293047,score_only,emogi
...,...,...,...,...,...,...,...
38734,ENSG00000169962,0.020044,4,False,-5.293305,emb_only,emogi
38735,ENSG00000182393,0.018414,4,False,-5.293305,emb_only,emogi
38736,ENSG00000198183,0.026527,4,False,-5.293305,emb_only,emogi
38737,ENSG00000186190,0.019796,4,False,-5.293305,emb_only,emogi
38738,ENSG00000137674,0.025553,4,False,-5.293305,emb_only,emogi

In [13]:
paper_cancer_genes[paper_cancer_genes["label"] == True]

,gene_id,pred,fold,label,original_score,method,model
0,ENSG00000133703,5.293305,0,True,5.293305,score_only,emogi
1,ENSG00000141646,5.293240,0,True,5.293240,score_only,emogi
3,ENSG00000166949,5.293138,0,True,5.293138,score_only,emogi
4,ENSG00000157764,5.293047,0,True,5.293047,score_only,emogi
8,ENSG00000160789,5.291928,0,True,5.291928,score_only,emogi
...,...,...,...,...,...,...,...
38169,ENSG00000140945,0.022025,4,True,-2.697413,emb_only,emogi
38350,ENSG00000134443,0.021568,4,True,-3.516196,emb_only,emogi
38357,ENSG00000104660,0.020966,4,True,-3.568731,emb_only,emogi
38456,ENSG00000175832,0.016614,4,True,-4.091980,emb_only,emogi
38726,ENSG00000242110,0.135326,4,True,-5.293205,emb_only,emogi

In [14]:
paper_cancer_genes_preprocessed = pd.read_csv('../../../../../../../../s/project/gene_embedding/cancer_pred/emogi_preprocessed.tsv', sep='\t')
paper_cancer_genes_preprocessed

               gene_id  label      pred
0      ENSG00000100393   True  5.293305
1      ENSG00000133703   True  5.293305
2      ENSG00000155657  False  5.293305
3      ENSG00000284792   True  5.293305
4      ENSG00000039068   True  5.293305
...                ...    ...       ...
13622  ENSG00000266200  False -5.293305
13623  ENSG00000125375  False -5.293305
13624  ENSG00000173662  False -5.293305
13625  ENSG00000197084  False -5.293305
13626  ENSG00000102924  False -5.293305

[13627 rows x 3 columns]

In [15]:
paper_cancer_genes_preprocessed[paper_cancer_genes_preprocessed["label"] == True]

               gene_id  label      pred
0      ENSG00000100393   True  5.293305
1      ENSG00000133703   True  5.293305
3      ENSG00000284792   True  5.293305
4      ENSG00000039068   True  5.293305
5      ENSG00000121879   True  5.293305
...                ...    ...       ...
12450  ENSG00000164919   True -4.540577
12666  ENSG00000164398   True -4.793728
13165  ENSG00000163319   True -5.223590
13247  ENSG00000172409   True -5.254834
13541  ENSG00000242110   True -5.293205

[796 rows x 3 columns]

In [16]:
paper_cancer_genes_preprocessed['pred'] = paper_cancer_genes_preprocessed['pred'] > 0

In [17]:
paper_cancer_genes_preprocessed

               gene_id  label   pred
0      ENSG00000100393   True   True
1      ENSG00000133703   True   True
2      ENSG00000155657  False   True
3      ENSG00000284792   True   True
4      ENSG00000039068   True   True
...                ...    ...    ...
13622  ENSG00000266200  False  False
13623  ENSG00000125375  False  False
13624  ENSG00000173662  False  False
13625  ENSG00000197084  False  False
13626  ENSG00000102924  False  False

[13627 rows x 3 columns]

In [18]:
paper_cancer_genes_preprocessed.to_csv('../preprocessed_data/emogi_preprocessed.tsv', sep='\t', index=False)

# OncoVar

In [19]:
oncoVar_cancer_genes = pd.read_csv('../../../../../../../../s/project/gene_embedding/cancer_pred/emogi_prediction.tsv', sep='\t')
oncoVar_cancer_genes

,gene_id,pred,fold,label,original_score,method,model
0,ENSG00000133703,5.293305,0,True,5.293305,score_only,emogi
1,ENSG00000141646,5.293240,0,True,5.293240,score_only,emogi
2,ENSG00000197694,5.293193,0,False,5.293193,score_only,emogi
3,ENSG00000166949,5.293138,0,True,5.293138,score_only,emogi
4,ENSG00000157764,5.293047,0,True,5.293047,score_only,emogi
...,...,...,...,...,...,...,...
38734,ENSG00000169962,0.020044,4,False,-5.293305,emb_only,emogi
38735,ENSG00000182393,0.018414,4,False,-5.293305,emb_only,emogi
38736,ENSG00000198183,0.026527,4,False,-5.293305,emb_only,emogi
38737,ENSG00000186190,0.019796,4,False,-5.293305,emb_only,emogi
38738,ENSG00000137674,0.025553,4,False,-5.293305,emb_only,emogi

In [20]:
oncoVar_cancer_genes[paper_cancer_genes["label"] == True]

,gene_id,pred,fold,label,original_score,method,model
0,ENSG00000133703,5.293305,0,True,5.293305,score_only,emogi
1,ENSG00000141646,5.293240,0,True,5.293240,score_only,emogi
3,ENSG00000166949,5.293138,0,True,5.293138,score_only,emogi
4,ENSG00000157764,5.293047,0,True,5.293047,score_only,emogi
8,ENSG00000160789,5.291928,0,True,5.291928,score_only,emogi
...,...,...,...,...,...,...,...
38169,ENSG00000140945,0.022025,4,True,-2.697413,emb_only,emogi
38350,ENSG00000134443,0.021568,4,True,-3.516196,emb_only,emogi
38357,ENSG00000104660,0.020966,4,True,-3.568731,emb_only,emogi
38456,ENSG00000175832,0.016614,4,True,-4.091980,emb_only,emogi
38726,ENSG00000242110,0.135326,4,True,-5.293205,emb_only,emogi