In [56]:
import pandas as pd
import numpy as np

# Mito predictions

In [57]:
mito_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S7_Mito_predictions.tsv', sep='\t')
mito_predictions

               gene_id  target          pred disease         emb  fold
0      ENSG00000110955   False  9.985855e-01    mito       OMICS     3
1      ENSG00000023228    True  9.858380e-01    mito       OMICS     4
2      ENSG00000189043    True  9.827512e-01    mito       OMICS     3
3      ENSG00000137547   False  9.809819e-01    mito       OMICS     1
4      ENSG00000159199   False  9.639758e-01    mito       OMICS     1
...                ...     ...           ...     ...         ...   ...
58984  ENSG00000289549   False  3.753921e-09    mito  STRING_EXP     3
58985  ENSG00000289690   False  3.753921e-09    mito  STRING_EXP     3
58986  ENSG00000289700   False  3.753921e-09    mito  STRING_EXP     3
58987  ENSG00000289747   False  3.753921e-09    mito  STRING_EXP     3
58988  ENSG00000290149   False  3.753921e-09    mito  STRING_EXP     3

[58989 rows x 6 columns]

In [58]:
print(mito_predictions[mito_predictions['emb'] == 'OMICS'].shape[0])
print(mito_predictions[mito_predictions['emb'] == 'STRING'].shape[0])
print(mito_predictions[mito_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [59]:
mito_predictions_processed = mito_predictions.loc[mito_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
mito_predictions_processed.to_csv('../preprocessed_data/mito_genes.csv', index=False)

# Opthamology Predictions

In [60]:
opthamology_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S8_Ophthalmology_predictions.tsv', sep='\t')
opthamology_predictions

               gene_id  target          pred        disease         emb  fold
0      ENSG00000000005   False  5.000000e-01  Ophthalmology       OMICS     3
1      ENSG00000001461   False  5.000000e-01  Ophthalmology       OMICS     3
2      ENSG00000001497   False  5.000000e-01  Ophthalmology       OMICS     3
3      ENSG00000001631   False  5.000000e-01  Ophthalmology       OMICS     3
4      ENSG00000003056   False  5.000000e-01  Ophthalmology       OMICS     3
...                ...     ...           ...            ...         ...   ...
58984  ENSG00000132313   False  1.054290e-06  Ophthalmology  STRING_EXP     4
58985  ENSG00000229292   False  9.188249e-07  Ophthalmology  STRING_EXP     4
58986  ENSG00000197345   False  8.095930e-07  Ophthalmology  STRING_EXP     4
58987  ENSG00000135900   False  7.699742e-07  Ophthalmology  STRING_EXP     4
58988  ENSG00000112081   False  5.658241e-07  Ophthalmology  STRING_EXP     4

[58989 rows x 6 columns]

In [61]:
print(opthamology_predictions[opthamology_predictions['emb'] == 'OMICS'].shape[0])
print(opthamology_predictions[opthamology_predictions['emb'] == 'STRING'].shape[0])
print(opthamology_predictions[opthamology_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [62]:
opthamology_predictions_processed = opthamology_predictions.loc[opthamology_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
opthamology_predictions_processed.to_csv('../preprocessed_data/opthamology_genes.csv', index=False)

# Neurology Predictions

In [63]:
neurology_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S9_Neurology_predictions.tsv', sep='\t')
neurology_predictions

               gene_id  target          pred    disease         emb  fold
0      ENSG00000077522   False  6.827557e-01  Neurology       OMICS     4
1      ENSG00000159173   False  6.346192e-01  Neurology       OMICS     5
2      ENSG00000196218    True  6.206573e-01  Neurology       OMICS     2
3      ENSG00000081248    True  5.523387e-01  Neurology       OMICS     5
4      ENSG00000143632    True  5.414254e-01  Neurology       OMICS     1
...                ...     ...           ...        ...         ...   ...
58984  ENSG00000170542   False  1.124948e-06  Neurology  STRING_EXP     1
58985  ENSG00000100453   False  1.124575e-06  Neurology  STRING_EXP     1
58986  ENSG00000176871   False  7.892506e-07  Neurology  STRING_EXP     1
58987  ENSG00000134061   False  6.283760e-07  Neurology  STRING_EXP     1
58988  ENSG00000205846   False  5.641161e-07  Neurology  STRING_EXP     1

[58989 rows x 6 columns]

In [64]:
print(neurology_predictions[neurology_predictions['emb'] == 'OMICS'].shape[0])
print(neurology_predictions[neurology_predictions['emb'] == 'STRING'].shape[0])
print(neurology_predictions[neurology_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [65]:
opthamology_predictions_processed = opthamology_predictions.loc[opthamology_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
opthamology_predictions_processed.to_csv('../preprocessed_data/opthamology_genes.csv', index=False)

# Inborn Errors of Immunity Predictions

In [66]:
inborn_errors_immunity_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S10_Inborn_Errors_of_Immunity_predictions.tsv', sep='\t')
inborn_errors_immunity_predictions

               gene_id  target          pred disease         emb  fold
0      ENSG00000197629   False  9.465168e-01     IEI       OMICS     4
1      ENSG00000009790   False  6.762534e-01     IEI       OMICS     4
2      ENSG00000001036   False  5.000000e-01     IEI       OMICS     2
3      ENSG00000002330   False  5.000000e-01     IEI       OMICS     2
4      ENSG00000002586   False  5.000000e-01     IEI       OMICS     2
...                ...     ...           ...     ...         ...   ...
58984  ENSG00000289692   False  6.249030e-11     IEI  STRING_EXP     4
58985  ENSG00000289710   False  6.249030e-11     IEI  STRING_EXP     4
58986  ENSG00000289746   False  6.249030e-11     IEI  STRING_EXP     4
58987  ENSG00000289767   False  6.249030e-11     IEI  STRING_EXP     4
58988  ENSG00000290149   False  6.249030e-11     IEI  STRING_EXP     4

[58989 rows x 6 columns]

In [67]:
print(inborn_errors_immunity_predictions[inborn_errors_immunity_predictions['emb'] == 'OMICS'].shape[0])
print(inborn_errors_immunity_predictions[inborn_errors_immunity_predictions['emb'] == 'STRING'].shape[0])
print(inborn_errors_immunity_predictions[inborn_errors_immunity_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [68]:
inborn_errors_immunity_processed = inborn_errors_immunity_predictions.loc[inborn_errors_immunity_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
inborn_errors_immunity_processed.to_csv('../preprocessed_data/inborn_errors_immunity_genes.csv', index=False)

# Neuromuscular_predictions

In [69]:
neurology_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S9_Neurology_predictions.tsv', sep='\t')
neurology_predictions

               gene_id  target          pred    disease         emb  fold
0      ENSG00000077522   False  6.827557e-01  Neurology       OMICS     4
1      ENSG00000159173   False  6.346192e-01  Neurology       OMICS     5
2      ENSG00000196218    True  6.206573e-01  Neurology       OMICS     2
3      ENSG00000081248    True  5.523387e-01  Neurology       OMICS     5
4      ENSG00000143632    True  5.414254e-01  Neurology       OMICS     1
...                ...     ...           ...        ...         ...   ...
58984  ENSG00000170542   False  1.124948e-06  Neurology  STRING_EXP     1
58985  ENSG00000100453   False  1.124575e-06  Neurology  STRING_EXP     1
58986  ENSG00000176871   False  7.892506e-07  Neurology  STRING_EXP     1
58987  ENSG00000134061   False  6.283760e-07  Neurology  STRING_EXP     1
58988  ENSG00000205846   False  5.641161e-07  Neurology  STRING_EXP     1

[58989 rows x 6 columns]

In [70]:
print(neurology_predictions[neurology_predictions['emb'] == 'OMICS'].shape[0])
print(neurology_predictions[neurology_predictions['emb'] == 'STRING'].shape[0])
print(neurology_predictions[neurology_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [71]:
neurology_predictions_processed = neurology_predictions.loc[neurology_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
neurology_predictions_processed.to_csv('../preprocessed_data/neurology_genes.csv', index=False)

# Neuromuscular Predictions

In [72]:
neuromuscular_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S11_Neuromuscular_predictions.tsv', sep='\t')
neuromuscular_predictions

               gene_id  target          pred        disease         emb  fold
0      ENSG00000128591    True  7.607837e-01  neuromuscular       OMICS     5
1      ENSG00000081248    True  6.467219e-01  neuromuscular       OMICS     5
2      ENSG00000111245   False  6.401634e-01  neuromuscular       OMICS     4
3      ENSG00000000003   False  5.000000e-01  neuromuscular       OMICS     2
4      ENSG00000000419    True  5.000000e-01  neuromuscular       OMICS     2
...                ...     ...           ...            ...         ...   ...
58984  ENSG00000289690   False  1.149047e-08  neuromuscular  STRING_EXP     1
58985  ENSG00000289700   False  1.149047e-08  neuromuscular  STRING_EXP     1
58986  ENSG00000289722   False  1.149047e-08  neuromuscular  STRING_EXP     1
58987  ENSG00000289760   False  1.149047e-08  neuromuscular  STRING_EXP     1
58988  ENSG00000289768   False  1.149047e-08  neuromuscular  STRING_EXP     1

[58989 rows x 6 columns]

In [73]:
print(neuromuscular_predictions[neuromuscular_predictions['emb'] == 'OMICS'].shape[0])
print(neuromuscular_predictions[neuromuscular_predictions['emb'] == 'STRING'].shape[0])
print(neuromuscular_predictions[neuromuscular_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [74]:
neuromuscular_predictions_processed = neuromuscular_predictions.loc[neuromuscular_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
neuromuscular_predictions_processed.to_csv('../preprocessed_data/neuromuscular_genes.csv', index=False)

# Epilepsy Predictions

In [75]:
epilepsy_predictions = pd.read_csv('../supplementary_tables/Supplementary_Table_S12_Epilepsy_predictions.tsv', sep='\t')
epilepsy_predictions

               gene_id  target          pred   disease         emb  fold
0      ENSG00000149970   False  2.371014e-01  epilepsy       OMICS     4
1      ENSG00000157087   False  2.214993e-01  epilepsy       OMICS     2
2      ENSG00000144290   False  2.166967e-01  epilepsy       OMICS     4
3      ENSG00000104833   False  2.051348e-01  epilepsy       OMICS     5
4      ENSG00000166862   False  1.927331e-01  epilepsy       OMICS     5
...                ...     ...           ...       ...         ...   ...
58984  ENSG00000289604   False  2.492357e-07  epilepsy  STRING_EXP     4
58985  ENSG00000289722   False  2.492357e-07  epilepsy  STRING_EXP     4
58986  ENSG00000289764   False  2.492357e-07  epilepsy  STRING_EXP     4
58987  ENSG00000289809   False  2.492357e-07  epilepsy  STRING_EXP     4
58988  ENSG00000290149   False  2.492357e-07  epilepsy  STRING_EXP     4

[58989 rows x 6 columns]

In [76]:
print(epilepsy_predictions[epilepsy_predictions['emb'] == 'OMICS'].shape[0])
print(epilepsy_predictions[epilepsy_predictions['emb'] == 'STRING'].shape[0])
print(epilepsy_predictions[epilepsy_predictions['emb'] == 'STRING_EXP'].shape[0])

19663
19663
19663

In [77]:
epilepsy_predictions_processed = epilepsy_predictions.loc[epilepsy_predictions['emb'] == 'STRING_EXP', ['gene_id', 'target']]
epilepsy_predictions_processed.to_csv('../preprocessed_data/epilepsy_genes.csv', index=False)